// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package clock

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func clockContent(tz string, format string, showSeconds bool, showDate bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"clock-widget\" data-clock=\"1\" data-tz=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(tz)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/widgets/clock/clock.templ`, Line: 7, Col: 14}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-format=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(format)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/widgets/clock/clock.templ`, Line: 8, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" data-show-seconds=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(boolAttr(showSeconds))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/widgets/clock/clock.templ`, Line: 9, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" data-show-date=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(boolAttr(showDate))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/widgets/clock/clock.templ`, Line: 10, Col: 37}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if showDate {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"clock-date\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"clock-time-row\"><span class=\"clock-hours-minutes\"></span> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if showSeconds {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<span class=\"clock-seconds\"></span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div></div><script>\n\t\t(function () {\n\t\t\tvar root = document.currentScript.previousElementSibling;\n\t\t\tvar tz = root.dataset.tz || 'UTC';\n\t\t\tvar use12h = root.dataset.format === '12h';\n\t\t\tvar showSecs = root.dataset.showSeconds === 'true';\n\t\t\tvar showDate = root.dataset.showDate === 'true';\n\n\t\t\tvar hmEl = root.querySelector('.clock-hours-minutes');\n\t\t\tvar secEl = root.querySelector('.clock-seconds');\n\t\t\tvar dateEl = root.querySelector('.clock-date');\n\n\t\t\tvar timeFmt = new Intl.DateTimeFormat('en-US', {\n\t\t\t\ttimeZone: tz,\n\t\t\t\thour: '2-digit', minute: '2-digit',\n\t\t\t\thour12: use12h,\n\t\t\t});\n\t\t\tvar secFmt = showSecs ? new Intl.DateTimeFormat('en-US', {\n\t\t\t\ttimeZone: tz, second: '2-digit', hour12: false,\n\t\t\t}) : null;\n\t\t\tvar dateFmt = showDate ? new Intl.DateTimeFormat('en-US', {\n\t\t\t\ttimeZone: tz,\n\t\t\t\tweekday: 'long', year: 'numeric', month: 'long', day: 'numeric',\n\t\t\t}) : null;\n\n\t\t\tfunction tick() {\n\t\t\t\tvar now = new Date();\n\t\t\t\tif (hmEl) hmEl.textContent = timeFmt.format(now);\n\t\t\t\tif (secEl && secFmt) secEl.textContent = secFmt.format(now).replace(/^0/, '');\n\t\t\t\tif (dateEl && dateFmt) dateEl.textContent = dateFmt.format(now);\n\t\t\t}\n\n\t\t\ttick();\n\t\t\tvar id = setInterval(tick, 1000);\n\n\t\t\t// Stop ticking if the element is removed from the DOM (widget deleted/refreshed)\n\t\t\tnew MutationObserver(function (_, obs) {\n\t\t\t\tif (!document.contains(root)) { clearInterval(id); obs.disconnect(); }\n\t\t\t}).observe(document.body, { childList: true, subtree: true });\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func boolAttr(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

var _ = templruntime.GeneratedTemplate
